# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - id: kahi
    main: ./cmd/kahi
    binary: kahi
    env:
      - CGO_ENABLED=0
      - GOFIPS140=v1.0.0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/kahiteam/kahi/internal/version.Version={{.Version}}
      - -X github.com/kahiteam/kahi/internal/version.Commit={{.Commit}}
      - -X github.com/kahiteam/kahi/internal/version.Date={{.Date}}
      - -X github.com/kahiteam/kahi/internal/version.GoVersion={{.Env.GOVERSION}}
      - -X github.com/kahiteam/kahi/internal/version.FIPS=true

archives:
  - id: kahi
    ids:
      - kahi
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - cmd/kahi/kahi.toml

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: "^feat"
    - title: Bug Fixes
      regexp: "^fix"
    - title: Performance
      regexp: "^perf"
    - title: Other
      order: 999
  filters:
    exclude:
      - "^Merge"

release:
  github:
    owner: kahiteam
    name: kahi
  draft: false
  prerelease: auto
  make_latest: true
  name_template: "{{.ProjectName}} v{{.Version}}"
