name: Bug Report
description: Report a bug in Kahi
labels: ["bug"]
body:
  - type: input
    id: kahi-version
    attributes:
      label: Kahi version
      description: Output of `kahi version` or the Git commit hash.
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go version
      description: Output of `go version`.
      placeholder: "go1.26.0 linux/amd64"
    validations:
      required: true

  - type: input
    id: os-arch
    attributes:
      label: OS and architecture
      description: Operating system and CPU architecture.
      placeholder: "Ubuntu 24.04 / amd64"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Create config file with ...
        2. Run `kahi start`
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened. Include log output if available.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other information (config snippets, log files, screenshots).
    validations:
      required: false
